/* This file is automatically generated with "make include/build_env.h". DO NOT EDIT */

#ifndef _BUILD_ENV_H
#define _BUILD_ENV_H

#define BUILD_ENV_UNAME "Linux mustapha-virtual-machine 4.15.0-39-generic #42~16.04.1-Ubuntu SMP Wed Oct 24 17:09:54 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux"
#define BUILD_ENV_DATE "2019年 04月 28日 星期日 14:54:46 CST"
#define BUILD_ENV_SRCDIR "/opt/rt-n56u/trunk/user/samba3/source"
#define BUILD_ENV_BUILDDIR "/opt/rt-n56u/trunk/user/samba3/source"
#define BUILD_ENV_USER "root"
#define BUILD_ENV_HOST "mustapha-virtual-machine"
#define BUILD_ENV_COMPILER "/opt/rt-n56u/toolchain-mipsel/toolchain-3.4.x/bin/mipsel-linux-uclibc-gcc"
#endif /* _BUILD_ENV_H */
